### ISSUE TITLE
Issue with filter

### ISSUE THREAD

**Issue by marcadella** [lihaoyi/scala.rx#122] opened 2018-12-07 09:59 UTC
```
val v = Var(0)
val filtered = v.filter(_ == 0)
v.trigger(println(s"v: ${v.now}"))
filtered.trigger(println(s"filtered: ${filtered.now}"))
v() = 2
v() = 0
```
should print:
```
v: 0
filtered: 0
v: 2
v: 0
filtered: 0 
```
But with v4.0, "filtered: 0" is only printed once (before "v: 2"). That is not the expected behavior.

A related issue is when calling filtered.triggerLater, the side effect should not be executed in case the initial value is not 0. It is just about checking the filtering condition and if it doesn't match you call triggerLater instead of trigger. Unfortunately because of the previous error mentioned this won't work well either.

**Comment by cornerman** [comment] 2018-12-07 10:05
@marcadella Thanks for the issue.

> But with v4.0, "filtered: 0" is only printed once (before "v: 2"). That is not the expected behavior.

I think, this is the expected behaviour, because an `Rx` only triggers if the value has changed. As for `filtered` in your example. The first value is `0` and the second value is `0` again - therefore it only emits the `0` once. For `v`, there should be three triggers `0`, `2`, `0`.

> A related issue is when calling filtered.triggerLater

Could you elaborate on this one?

**Comment by marcadella** [comment] 2018-12-07 10:07
Actually it turns out that 
```
val v = Var(1)
val filtered = v.filter(_ == 0)
v.trigger(println(s"v: ${v.now}"))
filtered.triggerLater(println(s"filtered: ${filtered.now}"))
v() = 2
v() = 0
v() = 3
v() = 0
v() = 4
```
prints

```
v: 1
v: 2
filtered: 0
v: 0
v: 3
v: 0
v: 4
```

So it seems that filter executes the side effect only once which is really not what one expects!

**Comment by cornerman** [comment] 2018-12-07 10:14
Why is that not the expected behaviour?

It matches how scala.rx works. As mentioned before, an `Rx` only triggers if the value really changes. The value of `v` changes 5 times. But the filter makes `filtered` only trigger once. That is when you set `v() = 0` the first time. Therefore trigger and triggerLater will only be called once.

You have to see that with `filter(_ == 0)` you are creating an rx that will only ever trigger once, because it can only be `0` from the start or eventually change to `0`. After that it cannot change to any other value and will never trigger again.

**Comment by marcadella** [comment] 2018-12-07 10:14
Thanks for your quick answer. Let's take the first code snippet again:
```
val v = Var(0)
val filtered = v.filter(_ == 0)
v.trigger(println(s"v: ${v.now}"))
filtered.trigger(println(s"filtered: ${filtered.now}"))
v() = 2
v() = 0
```
This is what I expect from the filter function:
```
v = 0 | filtered triggers with 0 (since initialization)
v = 2 | filtered doesn't trigger since 2 != 0
v = 0 | filtered triggers since 0 ==0
```
But this is not what happens since "filtered: 0" is printed only once.

**Comment by cornerman** [comment] 2018-12-07 10:15
> This is what I expect from the filter function:

What really happens is this:
```
v = 0 | filtered triggers with 0 (since initialization)
v = 2 | filtered doesn't trigger since 2 != 0
v = 0 | filtered doesn't trigger since it already has the correct value 0
```

**Comment by marcadella** [comment] 2018-12-07 10:18
Sorry the time I wrote my answer you had written yours in the meantime. Okey I understand now! Thanks a lot =)

**Comment by cornerman** [comment] 2018-12-07 10:20
Great, no worries. Please close the issue, if you think this is resolved.

**Comment by cornerman** [comment] 2018-12-07 10:48
You can do it the way, you are mentioning: `v.trigger(if (v.now == 0) doSomething)` or `v.foreach(v => if(v == 0) doSomething)`

**Closed** 2018-12-07 11:08 UTC
